### ISSUE TITLE
Formatowanie kodu

### ISSUE THREAD

**Issue by siniarskimar** [siniarskimar/stock-predictions#6]
Zauważyłem że pewne zmiany wykrywane przez gita są skutkiem innych ustawień formatowania.

Proponuje `.editorconfig` oraz korzystanie z autopep8.

```editorconfig
root = true

[*.py]
indent_style = space
indent_size = 4
charset = utf-8
```

```toml
# pyproject.toml
[tool.autopep8]
max_line_length=80
in-place=true
recursive=true
aggressive=3
```
